version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9301:9300"
    environment:
      - xpack.security.enabled=true  # enable authentication
      - network.host=127.0.0.1
      - http.host=0.0.0.0
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=Admin_123456
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - bootstrap.memory_lock=true
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elasticsearch-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=Admin_123456
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elasticsearch-net

networks:
  elasticsearch-net:
    driver: bridge